
"""Auto‑generate patch files (offline stub)."""
import pathlib, datetime

def make_patch(file_path: str) -> str:
    dst = pathlib.Path(file_path)
    dst.parent.mkdir(parents=True, exist_ok=True)
    if not dst.exists():
        dst.write_text(f"# Auto‑generated by ORION on {datetime.datetime.utcnow().isoformat()}\n")
        return f"Created {dst}"
    return f"{dst} already exists."

if __name__ == '__main__':
    import sys, json
    print(json.dumps(make_patch(sys.argv[1] if len(sys.argv) > 1 else 'demo.py')))
