"""builder.gen_patch
---------------------------------
Creates or overwrites a file with a basic, compilable Python stub.
Used when the AI back‑end is unavailable.
"""
from pathlib import Path
import datetime, textwrap, json, sys

STUB = textwrap.dedent("""\
    # Auto‑generated by ORION on {ts}

    def main():
        print("🔧 {path} ready")
""")

def make_patch(path: str) -> str:
    dst = Path(path)
    dst.parent.mkdir(parents=True, exist_ok=True)
    code = STUB.format(ts=datetime.datetime.utcnow().isoformat(), path=path)
    dst.write_text(code)
    return path

def main():
    path = sys.argv[1] if len(sys.argv) > 1 else "demo.py"
    print(json.dumps({"generated": make_patch(path)}))

if __name__ == "__main__":
    main()
